//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dyc_craft {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm QuiltsAndQuilts;
		
		protected System.Web.UI.WebControls.Repeater quiltList;
		
		protected System.Web.UI.WebControls.TextBox QuiltName;
		
		protected System.Web.UI.WebControls.TextBox QuiltDescription;
		
		protected System.Web.UI.WebControls.TextBox QuiltImage;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Button button2;
		
		protected System.Web.UI.WebControls.Image testQuilt;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
	}
}
