//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dyc_craft {
	
	
	public partial class MainLayout {
		
		protected System.Web.UI.HtmlControls.HtmlAnchor mainNavHome;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor mainNavAbout;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder DefaultPagePlaceholder;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder AboutPagePlaceholder;
	}
}
